
default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: admin
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: christmaslist_development

test:
  <<: *default
  database: christmaslist_test


production:
  <<: *default
  host: ec2-107-21-221-107.compute-1.amazonaws.com
  database: dd5uuqsjc4gki
  username: jeruikcxfvbsgq
  password: <%= ENV['CHRISTMASLIST_DATABASE_PASSWORD'] %>
